import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "@/styles/variables.css"
import  "@/styles/variablesDark.css"

import "./globals.css"
import HeaderOutlet from "@/components/headerOutlet/HeaderOutlet";
import FooterOutlet from "@/components/footerOutlet/FooterOutlet";

import LayoutThemeProvider from "@/providers/LayoutThemeProvider";
import PageLoader from "@/app/PageLoader";


export default function RootLayout({ children }) {




    return (
  
  <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      

      <LayoutThemeProvider >
       <PageLoader>
           {children}
       </PageLoader>

      </LayoutThemeProvider>
      </body>
    </html>
  );
}
